name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: cargo test -p deno_core
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
